services:
  edgeshare:
    build: .
    container_name: edgeshare-server
    restart: always
    network_mode: "host"
    environment:
      - PORT=9999
      - DOCKER=true
    volumes:
      - ./uploads:/usr/src/app/uploads
